use std::fs;
use std::path::PathBuf;

use ab_glyph::{Font, FontRef, PxScale, ScaleFont, point};

const FONT_FIRST: u32 = 32;
const FONT_LAST: u32 = 126;
const FONT_WIDTH: usize = 14;
const FONT_HEIGHT: usize = 24;
// PxScale is the font's line height; 26 px gives an approximately 14 px advance.
const FONT_SCALE: PxScale = PxScale { x: 26.0, y: 26.0 };
const BASELINE: f32 = 18.5;

fn main() {
    assert_eq!(FONT_WIDTH * FONT_HEIGHT % 4, 0);
    let font =
        FontRef::try_from_slice(include_bytes!("../assets/LiberationMono-Regular.ttf")).expect("invalid font file");
    let glyph_count = (FONT_LAST - FONT_FIRST + 1) as usize;
    let mut pixels = vec![0u8; glyph_count * FONT_WIDTH * FONT_HEIGHT];
    let advance = font.as_scaled(FONT_SCALE).h_advance(font.glyph_id('M'));
    let left = (FONT_WIDTH as f32 - advance) / 2.0;

    for code in FONT_FIRST..=FONT_LAST {
        let ch = char::from_u32(code).unwrap();
        let glyph = font.glyph_id(ch).with_scale_and_position(FONT_SCALE, point(left, BASELINE));
        if let Some(outlined) = font.outline_glyph(glyph) {
            let bounds = outlined.px_bounds();
            outlined.draw(|x, y, coverage| {
                let px = bounds.min.x as i32 + x as i32;
                let py = bounds.min.y as i32 + y as i32;
                let alpha = (coverage.clamp(0.0, 1.0) * 255.0).round() as u8;
                if alpha == 0 {
                    return;
                }
                assert!(
                    (0..FONT_WIDTH as i32).contains(&px) && (0..FONT_HEIGHT as i32).contains(&py),
                    "glyph {ch:?} extends beyond its cell at ({px}, {py})"
                );
                let index =
                    (code - FONT_FIRST) as usize * FONT_WIDTH * FONT_HEIGHT + py as usize * FONT_WIDTH + px as usize;
                pixels[index] = alpha;
            });
        }
    }

    let src = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../src");
    fs::write(src.join("font.bin"), pixels).unwrap();
    fs::write(
        src.join("font.rs"),
        format!(
            "\
// Generated by `cargo run --manifest-path tools/fontgen/Cargo.toml`
// Rasterized from Liberation Mono Regular (SIL Open Font License 1.1).
// See tools/fontgen/assets/LICENSE.txt for the font license.

pub const FONT_FIRST: u32 = {FONT_FIRST};
pub const FONT_LAST: u32 = {FONT_LAST};
pub const FONT_WIDTH: u32 = {FONT_WIDTH};
pub const FONT_HEIGHT: u32 = {FONT_HEIGHT};
pub const FONT_PIXELS: &[u8] = include_bytes!(\"font.bin\");
"
        ),
    )
    .unwrap();
}
