use std::fmt::Write;
use std::fs;
use std::path::PathBuf;

use font8x8::{BASIC_FONTS, UnicodeFonts};

const FONT_FIRST: u32 = 32;
const FONT_LAST: u32 = 126;
const FONT_WIDTH: u32 = 8;
const FONT_HEIGHT: u32 = 8;

fn main() {
    let glyph_count = FONT_LAST - FONT_FIRST + 1;
    let mut out = String::new();

    writeln!(&mut out, "#![allow(dead_code)]").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(&mut out, "// Generated by `cargo run --manifest-path tools/fontgen/Cargo.toml`").unwrap();
    writeln!(&mut out, "// Source: font8x8 0.3.1").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(&mut out, "pub const FONT_FIRST: u32 = {FONT_FIRST};").unwrap();
    writeln!(&mut out, "pub const FONT_LAST: u32 = {FONT_LAST};").unwrap();
    writeln!(&mut out, "pub const FONT_WIDTH: u32 = {FONT_WIDTH};").unwrap();
    writeln!(&mut out, "pub const FONT_HEIGHT: u32 = {FONT_HEIGHT};").unwrap();
    writeln!(&mut out, "pub const FONT_GLYPHS: u32 = {glyph_count};").unwrap();
    writeln!(&mut out, "#[rustfmt::skip]").unwrap();
    writeln!(&mut out, "pub const FONT_ROWS: [u32; {}] = [", glyph_count * FONT_HEIGHT).unwrap();

    for code in FONT_FIRST..=FONT_LAST {
        let ch = char::from_u32(code).unwrap();
        let glyph = BASIC_FONTS.get(ch).unwrap_or_else(|| panic!("missing glyph for {code}"));
        writeln!(&mut out, "    // {code} {ch:?}").unwrap();
        for row in glyph {
            writeln!(&mut out, "    0b{row:08b},").unwrap();
        }
    }

    writeln!(&mut out, "];").unwrap();

    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../src/font.rs");
    fs::write(path, out).unwrap();
}
