use std::fmt::Write;
use std::fs;
use std::path::PathBuf;

use ab_glyph::{Font, FontRef, PxScale, ScaleFont, point};

const FONT_FIRST: u32 = 32;
const FONT_LAST: u32 = 126;
const FONT_WIDTH: usize = 14;
const FONT_HEIGHT: usize = 24;
// PxScale is the font's line height; 26 px gives an approximately 14 px advance.
const FONT_SCALE: PxScale = PxScale { x: 26.0, y: 26.0 };
const BASELINE: f32 = 18.5;

fn main() {
    assert_eq!(FONT_WIDTH * FONT_HEIGHT % 4, 0);
    let font =
        FontRef::try_from_slice(include_bytes!("../assets/LiberationMono-Regular.ttf")).expect("invalid font file");
    let glyph_count = (FONT_LAST - FONT_FIRST + 1) as usize;
    let mut pixels = vec![0u8; glyph_count * FONT_WIDTH * FONT_HEIGHT];
    let advance = font.as_scaled(FONT_SCALE).h_advance(font.glyph_id('M'));
    let left = (FONT_WIDTH as f32 - advance) / 2.0;

    for code in FONT_FIRST..=FONT_LAST {
        let ch = char::from_u32(code).unwrap();
        let glyph = font.glyph_id(ch).with_scale_and_position(FONT_SCALE, point(left, BASELINE));
        if let Some(outlined) = font.outline_glyph(glyph) {
            let bounds = outlined.px_bounds();
            outlined.draw(|x, y, coverage| {
                let px = bounds.min.x as i32 + x as i32;
                let py = bounds.min.y as i32 + y as i32;
                let alpha = (coverage.clamp(0.0, 1.0) * 255.0).round() as u8;
                if alpha == 0 {
                    return;
                }
                assert!(
                    (0..FONT_WIDTH as i32).contains(&px) && (0..FONT_HEIGHT as i32).contains(&py),
                    "glyph {ch:?} extends beyond its cell at ({px}, {py})"
                );
                let index =
                    (code - FONT_FIRST) as usize * FONT_WIDTH * FONT_HEIGHT + py as usize * FONT_WIDTH + px as usize;
                pixels[index] = alpha;
            });
        }
    }

    let mut out = String::new();
    writeln!(&mut out, "// Generated by `cargo run --manifest-path tools/fontgen/Cargo.toml`").unwrap();
    writeln!(&mut out, "// Rasterized from Liberation Mono Regular (SIL Open Font License 1.1).").unwrap();
    writeln!(&mut out, "// See tools/fontgen/assets/LICENSE.txt for the font license.").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(&mut out, "pub const FONT_FIRST: u32 = {FONT_FIRST};").unwrap();
    writeln!(&mut out, "pub const FONT_LAST: u32 = {FONT_LAST};").unwrap();
    writeln!(&mut out, "pub const FONT_WIDTH: u32 = {FONT_WIDTH};").unwrap();
    writeln!(&mut out, "pub const FONT_HEIGHT: u32 = {FONT_HEIGHT};").unwrap();
    writeln!(&mut out, "#[rustfmt::skip]").unwrap();
    writeln!(&mut out, "pub const FONT_PIXELS: [u32; {}] = [", pixels.len() / 4).unwrap();
    for code in FONT_FIRST..=FONT_LAST {
        let start = (code - FONT_FIRST) as usize * FONT_WIDTH * FONT_HEIGHT;
        let ch = char::from_u32(code).unwrap();
        writeln!(&mut out, "    // {code} {ch:?}").unwrap();
        for row in pixels[start..start + FONT_WIDTH * FONT_HEIGHT].chunks(16) {
            write!(&mut out, "    ").unwrap();
            for (index, bytes) in row.chunks_exact(4).enumerate() {
                let word = u32::from_le_bytes(bytes.try_into().unwrap());
                write!(&mut out, "0x{word:08x},").unwrap();
                if index + 1 < row.len() / 4 {
                    write!(&mut out, " ").unwrap();
                }
            }
            writeln!(&mut out).unwrap();
        }
    }
    writeln!(&mut out, "];").unwrap();

    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../src/font.rs");
    fs::write(path, out).unwrap();
}
