// Generated by `cargo run --manifest-path tools/fontgen/Cargo.toml`
// Rasterized from Liberation Mono Regular (SIL Open Font License 1.1).
// See tools/fontgen/assets/LICENSE.txt for the font license.

pub const FONT_FIRST: u32 = 32;
pub const FONT_LAST: u32 = 126;
pub const FONT_WIDTH: u32 = 14;
pub const FONT_HEIGHT: u32 = 24;
pub const FONT_PIXELS: &[u8] = include_bytes!("font.bin");
